G.beemoviescript = {
"con este texto: ¿qué pasa peña bienvenidos una vez más",
"un nuevo día contigo conmigo con tremendo café",
"que ahora os tengo que contar algo em",
"pero a lo que vamos e café y balatro",
"ya no tengo ni idea no tengo ni la más",
"remota idea 15 16 no lo sé tío no lo sé",
"pero estamos un día más jugando al Balatrito",
"para que lo veáis ustedes para que veáis cómo manqueo",
"cómo hago buenas jugadas madre mía chavales madre mía",
"una aventura un poco loca siendo esta serie para mí",
"me apetece volver a jugar un mazo o sea un pozo",
"complicadito así que vamos a jugar el pozo morado",
"que tiene un un escala punto requeridos más rápido vale",
"o sea que te van a pedir todavía más puntos",
"va a haber como dinero te quitan un descarte",
"y la ciega inicial no te va a dar dinero",
"bueno pues tiramos para adelante ¿no seguro que no lo hacemos",
"n win type shit ¿no ¿qué tal gente que os contáis",
"que es de vuestra vida yo voy bastante bien yo voy",
"bastante chill un poco desorganizado y tal pero bueno",
"vamos tirando con lo que con lo que nos da el señor ¿no",
"ay como no como nos está dando este pedazo de color gente",
"lo que os iba a contar esto es algo muy grave ¿eh",
"lo de hoy no es café es un colacao lo siento",
"chicos lo siento es que me apetecía un montón un colacao",
"la verdad me apetecía un montonazo un colacao así que hoy",
"mira si has llegado a ver si has llegado a escuchar esto",
"que quede como secreto entre tú y yo no mucha",
"gente se ve estos vídeos no sé si habéis visto las",
"views en los vídeos pero no son ni de lejos",
"lo que pillo en los shorts así que como solo los",
"reales estáis aquí vamos a mantenerlo en secreto ¿vale",
"no se lo digáis a nadie que esto es colacado esta vez",
"por favor vale por favor vale em esto está muy",
"bien el problema es que no nos va a dar multiinicial",
"pero creo que en la tienda había el estaba el banderín",
"ese de los descartes podemos ir tirando con eso de momento",
"míralo mm ¿me pillo el banderín o me la juego",
"yo creo que merece la pena jugársela venga sí ¡uf esto",
"es duro ¿eh esto es malísimo de hecho esto es mucho",
"compromiso creo podríamos intentar ah venga vamos a intentarlo yo",
"vale 10 9 8 7 6 empezamos con una escalerita",
"podríamos haber jugado la J también pero bueno okay eso",
"va por un lado 8 7 6 5 Uy casi ¿eh",
"vale ¿qué más tenemos por aquí probablemente os haya parecido muy",
"mala idea coger ese Joker yo lo comparto pero de",
"nuevo n win ah ah ah doble pareja con esto",
"ay que no era doble madre mía estamos fatal ¿eh",
"por suerte tenemos aquí un trío que con esto creo",
"que salimos ya ¿no sí u hay que espabilar hay",
"que espabilar tampoco no me lo tengáis muy en cuenta entre",
"que no es café ¿vale y que no llevo mucho rato",
"despierto por favor no me lo tengáis en cuenta em jokers",
"reguleros estoy viendo por aquí vamos a ver qué sale de",
"esto a ver si sale una carta chulis el tema es",
"que esto tiene nos contaría para tal vamos a llevarnos esto",
"rerrol esto es bueno tío nada de esto nos da multi",
"¿eh vamos a pillarnos esto ah pero si esto es malísimo",
"madre mía madre mía hoy estamos jugando fatal ¿eh",
"hoy estamos jugando fatal vamos a jugar así vale okay",
"salimos del paso nos llevamos 3 dolarillos ta ta ta",
"ta ta esto nos va a hacer falta eso nos iba",
"a hacer falta hm dame esto vamos a empezar a tunear",
"cartas para ver si llegamos a esto eh la tienda incomodín",
"raro pasando tronco hay una J por ahí vamos a",
"jugar una mano basurita y bueno mira ya sé ya sé",
"que no hace muy buena sinergia esto con lo otro ¿vale",
"pero si pillamos unas poquillas de jotas creo que podríamos",
"llegar a algún lado ah tenemos un flush aquí tengo una",
"idea vamos a hacer este descarte pillo 5 euritos no no",
"hemos podido pillar ninguna pica que era lo cual era el",
"plan pero bueno venga venga venga ahí estamos ahora hacemos",
"así y yo creo que salimos ¿no porque entre el multi",
"de esto esto hay que un Uy pues no eh venga",
"con esto sí con esto sí nos la hemos jugado demasiado",
"creo yo nos la hemos jugado demasiado creo yo no va",
"a quedar otra que confiar en el poder del Joker Birday",
"mm mira para tener esto prefiero esto que además nos",
"va a dar $ sin fallar cada ronda claro como habíamos",
"cogido antes un nueve pues eso que nos llevamos el obviamente",
"hay que tirar un hydrofant lo vamos a tirar por aquí",
"por ejemplo ¿no no sé lo he tirado muy random si",
"si veis que se podía optimizar esa decisión pues dejarme un",
"comentario la verdad porque es que no tengo ni idea que",
"a todo esto lo de los comentarios me encanta de verdad",
"yo lamento no estar contestando a los comentarios que me estáis",
"dejando tío estos días la verdad que estado bastante liado",
"y eso entonces pues como que se me ha complicado un poco",
"la movida pero de verdad que me encanta que comentéis a",
"ver si ahora puedo sacar un ratillo y os pongo y",
"os respondo a cosillas mm estoy empezando a no ver",
"esto ¿eh vale no no no no we are so",
"back yo creo que salimos ¿no sí sí sí sí",
"uf bueno estamos rozando un poquillo lo que viene siendo la",
"derrota por suerte esto ya no ha dado el dinerito eso",
"es bueno ¿eh ah que sale de aquí vale vamos a",
"jugar em presisian creo eh vamos a hacer así y",
"así por ejemplo estamos farmeando esto todo lo posible ¿eh",
"por si no ha quedado claro ya vale Hyrofan perfecto hacemos",
"así ahora vale vale vale vale venga venga ahora lo",
"bueno es que ahora la ciega la ciega esta que no",
"nos daba dinero en un principio gracias a esto nos",
"da dinero básicamente 10 9 8 7 6 jugamos esto",
"y tiramos para adante esto nos va a dar 13 de",
"multi lo cual nos va a venir medio que para ir",
"tirando ah dos tres uy 2 3 cu 5",
"me falta ahí un seis maldita sea por suerte podemos jugar",
"esta doble pareja creo venga okay okay okay okay 3",
"cu 5 de nuevo nos falta el Bueno tenemos doble",
"pareja no nos importa tampoco mucho vale 15 de multi",
"vale vale vale vale we are so back we so",
"back venga hm interesante esto la verdad es que no",
"nos está haciendo mucho favor vamos a llevarnos esto y luego",
"si vemos qué tal vendemos este comodín porque es que no",
"está haciendo nada prácticamente ah vale esto por aquí espérate",
"podría jugar podría jugar flush aquí jugar color no no",
"tenemos color todavía ah mmm m voy haciendo un descarte",
"en verdad tío yo creo que sí ¿no venga vale ahora",
"sí tenemos color ¿no sí ah encima tenemos activación de",
"esto lo cual nos va a dar siete de multi que no",
"es mucho pero está nice doble pareja por aquí mm",
"y yo que sé así mismo ¿no vale a ver si suena",
"la flauta no son la flauta pero bueno salimos que es",
"lo que importa nos llevamos los 5 dolariños nice esto está",
"funi la verdad que haría más que esto em creo que",
"los indicados sería llevarse esto ¿vale y vamos a vender",
"no no vamos a vender nada nos vamos a abrir un",
"este y vamos a subir esto comienza con cero descartes pues",
"quizás ha sido mala idea ¿eh ah quizás ha sido",
"mala idea cogerse aquello ¡uf creo que de la única",
"manera de la que podemos salir de aquí es haciendo un",
"color de tréboles así que vamos a tener que buscarlo con",
"todas nuestras ganas fuera vale tenemos ya tres aquí madre",
"mía venga venga venga venga ay Dios mío que perdemos",
"venga venga venga un trebolillo por favor estamos fuera ¿verdad",
"venga vamos por favor ah ah no me voy a",
"fijar lo rojo que se me pone en la cara cuando",
"sufre una derrota maldita sea ay we try again la",
"verdad que ha sido una caca de partida por no decir",
"otras palabras más fuertes pero es que es que en verdad",
"hemos cogido Joker malísimo el el coger el Joker verde",
"esa ha sido la condena podríamos haber tomado muchas mejores",
"decisiones ya no me la juego más prometo que no me",
"la juego más venga vamos a jugar ya un poco normalito",
"em voy a tirar una R venga así mismo y vale",
"de nuevo roleamos de nuevo de nuevo me gustan mucho los",
"comentarios que recibo pero también es cierto que recibo algunos",
"que son en plan ay debería saber ¿no en plan el",
"el tema del backing tío el tema de que esto de",
"que la gente venga y me diga cómo se juega al",
"balatro y tal yo para empezar que no soy profesional ¿vale",
"creo que ya lo he dicho bastantes veces en en vídeos",
"de esto yo no soy pero ni mucho menos lo acabáis",
"de ver gente yo vengo aquí a jugar al balatro y",
"y que sea un poco lo que Dios quiera ah interesante",
"pero esto nos da multi nos vamos a quedar así para",
"adelante color de diamante y la de siempre ¿no okay vale",
"bien yo no soy profesional y agradezco que venga gente",
"a veces y diga \"Oye tío pues podría haber hecho tal",
"y podría haber hecho cual.\" Por ahora no he recibido",
"comentarios muy tóxicos sí que es cierto que recibió alguno",
"en plan y se coge eso en vez de pillarse lo",
"otro qué tonto no dicen que tonto pero es como \"Buah",
"¿cómo hace eso no sé qué criminal por favor.\" Pero",
"bien bien ahora mismo los comentarios están bastante bien ¿no",
"no me puedo quejar la verdad que no me puedo quejar",
"leñe bastante que recibo comentarios y visitas ¿no ay tío",
"se nota la falta de café ¿eh gente vosotros qué decís",
"mmm m no a quedar así porque eso me vale verga",
"venga ese color Bueno venga ese color venga ese madre mía",
"va a salir de todo menos diamantes queo vale gracias",
"mira mira mira mira cuántos diamantes nos quedan ocho vale en",
"la siguiente ya no salimos con un color de diamante ¿eh",
"cuidadito vale Missprint nice okay uh y esto ay",
"si tuviéramos algo de dinero estaría genial ¿eh mm comodín",
"inusual no gracias ahora mismo no muchas gracias venga hombre",
"vamos a jugar esto en verdad por cierto esto no se",
"ha activado ni una sola vez ¿eh la farsa del Joker",
"este tío comodine espacial es como un No está ahora mismo",
"no está la leche tío em pi sale ahora mismo hay",
"muchas cosas que nos interesan m a ver qué sale",
"bueno ve un poco sin comentarios me ha dejado eso ¿no",
"podríamos haber tirado también el Emperor a ver si salía el",
"High Pristes nos daba los dos planetitas y tal y cual",
"pero no ha sido el caso ah contiene tal sí pareja",
"pues vamos a ver qué apaño nos hace esto pues bastante",
"buen apaño la verdad no nos podemos quejar adió pero",
"eh y seré bobo tío oye estoy fatal ¿eh oye",
"estoy fatal es que ni me había Nos ha nos ha",
"atacado el mayor enemigo de Balatro la comprensión lectora estamos",
"básicamente a la merced de que Missprint nos echa un",
"cable madre mía vale vale vale vale vale vale se",
"ha salido se ha salido se ha salido se ha salido",
"madre mía qué mal tío qué mal bueno bueno bueno",
"ya está ya está ay por favor estamos fatal ¿eh",
"trance trance nos va a venir bien genera planetita así que",
"se lo voy a poner yo que sé a esto mismo y",
"para adelante por favor que suba de nivel una sola",
"vez el color aunque sea ¿eh es que madre mía me",
"tiene recontrapodridísimo es jug esto mira ahora sube de nivel",
"ahora ha subido de nivel la pareja tú para me chacota",
"colega venga hombre bien bien y planetita perfecto perfecto era",
"justo lo que queríamos vale esto va muy lento ¿eh",
"planetita de nuevo venga la pareja vale me la juego ¿qué",
"puedo decir gente me encanta el gambling Hex no vale",
"nada eh mira qué color más bonito lo subimos de nivel",
"bien qué buena qué buena ahí el Joker astronauta salvándonos",
"jugamos este color y para fuera madre mía qué cagadón tío",
"madre mía que todavía me estoy cagando encima con la última",
"ciega jefa aquella ¿eh es que de verdad la comprensión",
"lectora no ha podido ¿eh eso ha sido durísimo menos mal",
"que hemos podido salir del paso okay y para adelante",
"primera mano boca abajo ¡uf eso es duro ¿eh ¿dónde",
"solían estar los diamantes tío por aquí a ver qué sale",
"de aquí perfecto ni un solo diamante en parte era lo",
"que yo quería esto fuera a no ser que esto sea",
"un as que lo dudo muchísimo míralo hice bien en dudar",
"venga hombre como din espacial enróllate es más malo el",
"pobre es más malo o sea cuando cuando se activa es",
"como una fiesta tío pero ey mira yo creo que lleva",
"tocando ¿no ya iba siendo hora esto nos va a ayudar",
"bastante no podemos hacer algo como esto hacer así perfecto",
"perfecto muy útil lo que nos ha tocado ¿eh muy muy",
"útil sí señor bien Joker espacial bien al final me va",
"a tener que me voy a tener que callar la boca",
"al final me voy a tener que callar la boca con",
"el Joker espacial ¿vosotros confiáis en el Joker espacial tío",
"a mí la verdad que me cuesta bastante 1 con tres",
"a ver yo creo que este colega se tiene que ir",
"y tendría que entrar este el problema es que apenas tenemos",
"dinero ahora mismo nada tío venga carta más alta los",
"tipos de malos no se repiten no me va a pegar",
"con todo lo contrario ta ta ta ta ta venga bien",
"oye tío qué buena vale encima carta de planetita qué bueno",
"qué bien me va a sentar vámonos un bucha al café",
"vámonos bien uno con cuatro ya casi parece una carta de",
"de planeta iba a decir una carta metálica pues más cartas",
"de suerte y vamos a vamos a ver qué sale de",
"aquí júpiter excelente 1 con5 ya muy bien vale tirio",
"tiro podría hacer escalera de color si quisiera tío podríamos",
"buscarlo en verdad pero paso en verdad en verdad en",
"verdad en verdad venga venga venga venga la flautita sonó",
"la flautita nos vamos perfecto perfecto perfecto vale vale vale",
"venga hombre mm mm es que necesitamos el dinero ¿eh",
"¿hay alguna cosilla así para ganar dinero ahora esto de aquí",
"pues mira vamos a hacer así ang ¡uf esto es duro",
"¿eh ectoplasma men uno en tamaño de mano nos va a",
"destrozar eso necesitamos necesitamos el dinero necesitamos el dinero así",
"que voy a hacer esto creo venga ahora me salto esto",
"pillo dinerito y como tenemos tan buena suerte ahora jugamos",
"las cartas de suerte y nos van a dar 20 €",
"ah tío imagine vale no era mentira esta vez cuando juguemos",
"la carta de suerte nos va a dar 20 € Perfecto",
"tío enróllate era mentira ahora es cuando nos van a dar",
"los 20 € Fijarse fijarse 20 quería decir 20 de",
"multi ¿vale por favor prestar atención ¿vale prestar atención",
"al gameplay he dicho 20 de multi que de verdad ¿eh",
"okay ahora mismo nada de esto nos superinteresa mucho quizá un",
"stars pero es que esto es muy jugoso ¿eh vamos a",
"tirar de esto si me dan dinero yo casi siempre voy",
"a coger dinero ah pese a quien le pese vamos a",
"tirar esto por ejemplo ¿no así o podría simplemente hacer",
"esto que que son menos cartas pero al menos podemos Cada",
"carta de figura en tu mano tiene un tal a ver",
"y nada de esto nos vale así que así que así",
"que así que pasando perfecto color de primera encima momento nivel",
"13 ya oye Joker el espacial se está enrollando ¿eh",
"parece que no pero se enrolla venga esos 20 € gente",
"dadme 20 € tío hacerme un PayPal yo quiero un PayPal",
"ya vuestro quiero uno me hago el Patreon si si yo",
"hiciera un Patreon tío ¿qué clase de contenido siquiera podría ofrecer",
"yo a mí a mis viewers mapalatro ah temperan supongo no",
"sé a ver qué sale de aquí r o sigil",
"¡uf esto jugar demasiado ¿no mm pluto uhu joker economías",
"joker economías vamos a una puesta seis ya uy qué guapo",
"¿no ¿no veis qué guapo esto nos da $ en todas",
"las ciegas si quitáramos por ejemplo al Joger espacial y metiéramos",
"esto tendríamos un multiplicador de 1,5 yo creo o sea",
"da penilla esto es que esto nos da multi esto nos",
"hace falta sí o sí bueno quizás podríamos quitar uno de",
"estos dos y quedarnos tan tranquilos ¿no de hecho esto es",
"como esto al final yo creo que voy a quitar a",
"este no venga sí el dinero lo necesitamos tío el dinero",
"no hace falta yo quiero más planeta ahí está el Joker",
"Planeta el Joker Planeta tío le estoy poniendo todos los",
"nombres que se me ocurren joker el planeta de Agustini nice",
"ese dinero de verdad que nos va a venir muy bien",
"quizás no haya sido la mejor decisión pero es que de",
"verdad que pienso que ese dinero mira este colega otra vez",
"¿eh eh elige una de estas tres elige una de estas",
"tres no es ninguna de ellas es un planeta así que",
"pasando tranco loco los 20 € enrolló John Balatro es",
"increíble lo lejos que estamos llegando con esto a 1 con",
"se es que 8 7 6 43 ah tío enrolló",
"vale ey ey high pristes perfecto estamos así ahora ¿cuántas",
"cartas de suerte tenemos tío es loquísimo vale vale ya",
"perfecto para dentro esto en verdad bueno ¿eh esto en",
"verdad si suena la flauta suena fuerte lo cambio por esto",
"tío nos la jugamos es que claro como toque lo otro",
"n yo creo que merece la pena de san nos quedamos",
"así todas las picas se debilitan implica tréboles también pero como",
"nos da igual un poco ahora por esto eh taca taca",
"taca taca ta perfecto hacemos ahora sí y va a subir",
"de nivel y nos va a dar 20 € atentos eh ah",
"so close treble vale hm okay no nos vale nada",
"much nada tampoco pero bueno mira por fin da por dos",
"¿eh solo solo ha requerido siete antes para funcionar ah Urano",
"llega el verano y las manos en Urano vamos así el",
"arco de redención del comodín espacialillo espectacular ¿eh ahora eran",
"tréboles fuck vamos así por ejemplo dios santo de mi",
"vida confíen en el comodín espacial esto ha sido su arco",
"de redención ¿eh la leche high pristes ñaca ñaca y",
"tendría que habérmelos dejado aquí para quitarlos del pull pero",
"bueno me ha salido Júpiter igualmente okay ah ñaca ñacaña",
"nos quedamos así venga para adelante ahora son corazones pero",
"como estamos con este como tenemos este joker aquí madre",
"mía madre mía nice 16 Lel ¿qué sale de aquí",
"r de nuevo pues nos da un poco igual júpiter genera",
"dos cartas de tarot vamos a ver qué sale funciona ah",
"no se puede tener tanta suerte gente una poquita sí tanta",
"no ay quizá tendría que haber comprado el bouch en verdad",
"¿eh ahora es diamante por favor no descarte el sello azul",
"ah tanto no se le puede pedir a Balatro bastante que",
"está funcionando este colega estoy teniendo mucha suerte gente a",
"vosotros funcionaba así la verdad es que tenemos a este colega",
"desde el principio ¿eh funcionar debía funcionar quiero decir 20",
"€ y tú de oro miau miau mia miau miau",
"no planeta placa placa plaz a ver qué sale para",
"dentro no vamos a pillar ese sobre ahora es treble okay",
"pero esto lo quiero jugar tururum vamos a buscar el el",
"sello azul me cachi igualmente no creo que salgamos jugando",
"esto ¿no bueno es que esto mete bastante mm en",
"cuanto vea el sello azul le cuelo de eh ñaca",
"vale ¿qué tenemos por aquí hangedman Chariot creo que si",
"nos cargamos algo así nos podré ir bien y si metemos",
"esto oye nunca se sabe ¿no nunca se sabe cuándo puede",
"salir la build y esto por ejemplo vaya que suene la",
"flauta que no lo creo vamos a comprar esto también porque",
"apetece supongo pillamos esto y ahora es pica me da",
"igual porque voy a jugar todo esto y nos va a",
"dar 20 € no nos ha dado una cacota miau miau",
"miau plana planga planga planga muy bien funciona muy bien",
"necesitaríamos algo de retrigers tío algo de retrigers sería que te",
"cagas ¿eh sallos rojos y están movidas ¿vosotros no sabéis",
"el esfuerzo inhumano que estoy haciendo la novena puerta me he",
"puesto hasta nervioso eh gente yo creo que es el momento",
"me tengo que despedir de él tantos buenos momentos que nos",
"ha dado nos ha conseguido que color sea nivel 21 eh",
"es que esto y esto no puedo quitármelo esto he trabajado",
"demasiado con esto para para perder para echarlo todo a perder",
"ahora se tiene que ir 7 en los comentarios por favor",
"por el comodín espacial que creíamos que no iba a ser",
"una verga pero ha rentado tela ahora perqueo manifestemos perqueo",
"por favor manifestemos perqueo manifestemos perqueo manifestemos perqueo perqueo",
"manifestado atentos bueno bueno no es perqueo no es perqueo",
"no es perqueo pero es chicote es chicote es chicote es",
"chicote a la gente le flipa este tío a mí me",
"da yo reconozco que a mí me da un poco de",
"pereza ¿eh pero a la gente le flipa de hecho cuando",
"puse en el vídeo en el vídeo anterior el el meme",
"este de de que lo había subido ¿cómo se llama",
"balatro balatrec era em que salía ahí el chicote como",
"a punto de cargarse a la ciega jefe la gente lo",
"flipaba en plan chicot chicot a la gente le flipa tío",
"es como un fan favorite a mí yo lo siento chicos",
"yo no sé si subirme a vuestro barco ¿eh tengo mis",
"dudas o sea es bueno no es que sea un inútil",
"jorik me parece peo bueno Joric si te toca de principio",
"está guapo pero chicos tío que no mete ni multi ni",
"nada esto vosotros pensáis que ahora mismo tenemos dos Joker",
"que no que no meten mucho y os juro que no",
"estoy haciendo rage bait ¿eh os lo juro pero no",
"sé no sé tío no sé no sé bueno mira se",
"acaba de cargar la cieja jefe final tampoco esta esta era",
"la más la más flojilla de todas también te digo o",
"sea jugábamos una mano reordenábamos como hiciese falta y ya está",
"¿qué toca ahora por cierto corazón para darte gente podía",
"haber sido perqueo bueno vamos a jugar un rato con Chicot",
"me apetece ya ya que ha salido el colega ya que",
"ha salido el colega no le vamos a hacer feo okay",
"estándar no sé k esto por aquí ey ya lo",
"hemos desbloqueado let's go qué bueno paquete bufón para adelante",
"a ver si encontramos el sello azul gente ahora que toca",
"treble taca taca taca taca ta y dale ahí con",
"el plingui plingi claro que sí maldito sea chicote ¿cómo",
"era ¿qué era lo que decía ah pin pam truc",
"trucu ay Dios mío vosotros yo soy superfan de Pesadilla",
"en la cocina tío yo lo veía con mis padres lo",
"he visto con mi pareja está supergapo el programa a mí",
"me gusta mucho hay que tomárselo también con un poquito",
"de tal porque hay mucho teatro en eso al final pero",
"está guapo el tema de chicote es que esto ya para",
"qué no otorgas 5 no no quiero tus e pero",
"si es mi colega pum pam quizás no podría haber hecho",
"eso sobre otra carta ¿no pero bueno ya está hecho",
"diamantes oh yeah venga hombre 1 2 1 2 3",
"los 20 € por favor nada oye no hay manera",
"uh okay weird pero con esto salimos los 20 €",
"los 20 € por fin vale ey los retrigger qué",
"bueno ah pero es que no podemos tío es que no",
"podemos porque si quitáramos esto de medio esto ya prácticamente",
"perdería sentido habría que quitar esto en todo caso y",
"merece la pena quitar esto caso no sé lo quitamos en",
"verdad porque es que es muy yo no creo que sea",
"buena idea pero ya tengo curiosidad por ver a cuánto",
"se llega con los retriggers de esto porque es que esto",
"metería el por uno con las cinco cartas pero con esto",
"serían 10 por 1,5 eso es fuerte ¿eh aquí",
"sale lo pruebo tío venga podría haber vendido al chicote",
"podría haber vendido el chicote y no lo he hecho y",
"no lo hago por vosotros porque sé que os gusta",
"espero que no sea una de esas cosas que que no",
"que era un meme en verdad que nosotríamos archicot os mato",
"¿eh os desintegro o desintegro igualmente metemos bastante descártame",
"esto vamos a jugar esto y ya está plingui plingi",
"plingui pling ¡uf vamos a jugar este color y ahora",
"llegó la hora de la verdad vamos a ver cuánto hace",
"con los retriggers esto tendría que haberse ido para la",
"izquierda pues mete como como un millón y pico ¿no",
"bastante bien si me preguntan mm esto está bien y",
"para dentro esto un hermit que esto mete 25 ñan",
"whatever ya no tiene sentido comprobar estas cosas ya lo",
"que estamos buscando son barbaridad de rollo blueprint o algo",
"así hm para adante esto nos pide ahora diamante oh",
"yeah diamantes creo que de estas ya no salimos ¿eh",
"es una pena chicot solo nos pudo bendecir un ratillo con",
"su presencia pero qué ratillo ¿eh vale y ahora vamos",
"a hacerlo bien vamos a poner las cosas así vamos a",
"buscar a ver si hay mejores cartas esto es ligeramente mejor",
"¿no eh venga no me la voy a jugar más para",
"adelante 20 de multi 3 millones es potente es que es",
"potente es que es potente no sé yo con lo otro",
"quizá hubiésemos llegado a puntuaciones similares pero no creo yo",
"que Chicote foil ah imaginen la rueda asif care para",
"adante que tocadora pica vamos para adelante 3 hostia qué",
"poco ha hecho ¿no miau miau miau miau miau miau mia",
"mia mia mia mia mia miau mia miau miau mia mia",
"okay okay okay esto podría ser nuestro momento 7 eh",
"podría acabarse todo aquí lo veo perfectamente factible dependemos al",
"final de la última mano a ver y las cartas de",
"de Pica y de Trebol no estaban tan mejoradas como la",
"como los diamantes vale fue un placer haberos conocido chicos allá",
"vamos perfecto 20 de multi que se va a multiplicar 80,000",
"veces multiplicación de esto uy vale vale vale vale vale",
"we we are so back we are so back ahora",
"toca diamante excelente las cartas que tenemos tunear vale esto",
"es muy cacota vamos a poner esto aquí ya está uno",
"en siete cartas se saca boca abajo oh Dios mío",
"¿qué vamos a hacer con que no que está chicote con",
"nosotros por favor okay vamos a poner esto aquí venga 3",
"y habéis visto los vídeos esos de cómo era así como",
"avanza la tecnología observa este nuevo robot cómo lo ayuda",
"en todo lo que necesita me encantan esos vídeos ¿eh me",
"encantan esos vídeos soy superfan se los mando a mi colega",
"siempre que puedo son la leche okay jug esto así por",
"ejemp Bueno de verdad merece la pena que juguemos esto ¿cuántas",
"cartas de suerte nos quedan nos quedan poquillas ya ¿eh",
"o sea tendríamos que guardarnos esto mia mia mia mia mia",
"mia miau vamos a descartar esto creo por mucho que nos",
"pese creo que ha sido mala idea esta es la mano",
"que jugaríamos así que tendríamos que descartar esto nos va a",
"ser muy Esto no va a hacer falta esto nos va",
"a hacer falta lo que quiere decir tendría que Ay Dios",
"mío pero ¿por qué jugado la reina en vez del cuatro",
"seré bobo vale perfecto podemos jugar esto así esto va a",
"ir aquí y lo demás así al lío 20 de multi",
"20 € 40 de multi buah vaya sacada de mano",
"tío vaya sacada de mano no sé cómo estamos sobreviviendo",
"haría falta algo de cristal tío eso sería ya la leche",
"esto para dentro algo de cristal algo de cristal algo de",
"cristal ah nueve de pica yo que sé venga para dentro",
"nos da igual nos da igual no nos da igual nos",
"da igual nos da igual perfecto nos da igual 29 millones",
"vale yo creo que con lo de quizás con lo de",
"cristal sobrevivimos ¿eh y no y no va ni en",
"broma a ver alargando aquí lo inevitable tú vale ah",
"todo esto fuera vamos a jugar esto mal jugado porque esto",
"debería ir al principio pero bueno vale ahora vamos a jugar",
"esto y por último vamos a jugar esto aquí así así",
"así así escalera de color por la cara ¿no así",
"mismo o hacemos así claro porque si meto esto ya es",
"careta vale vamos a jugar así a tomar viento que sea",
"lo que Dios quiera gente 29 millones de puntos tenemos una",
"carta de cristal que se va a reactivar dos veces dudo",
"de las posibilidades de esto pero se puede intentar es lo",
"que vamos a hacer venga qué oscuro me veo ahora que",
"me fijo tengo que utilizar luz ah no era tan mal",
"intento no era tan mal intento hemos jugado bien lo hemos",
"jugado bien pese al que le pese por muy hater que",
"sea esa última se ha jugado bien se ha intentado se",
"ha hecho lo que se ha podido ay yo me lo",
"he pasado muy bien hemos hecho las tonterías que hemos querido",
"al final ha venido chicote a salvar la run basadini si",
"me preguntan pero bueno ha sido lo que ha sido gente",
"espero que os haya gustado el gameplay lamento de nuevo los",
"misplays del principio vosotros ya me tenéis que ir conociendo vosotros",
"sab tenéis que saber ya que cuando yo empiezo un",
"vídeo de esto a mí me apetece hintear un poco al",
"principio me apetece un poquito hacer el mongoloide al principio",
"y luego ya jugar un poco más en serio que también",
"hemos hecho chorradas aquí ¿eh al final esto va de",
"divertirse gente por favor no lo toméis muy en serio eso",
"espero que os haya gustado que no de mucho coraje como",
"juego me lo he pasado genial y un beso enorme ¿vale",
"suscribirse darle me gusta mandarme un beso en los comentarios",
"si habéis llegado hasta aquí y hasta luego adiós adiós",
"adiós adiós"


}